import Head from 'next/head'
import {PostCard} from '../components'
import {Categories} from '../components'
import {PostWidget} from '../components'
import { getPosts } from '../services'
import FeaturedPosts from '../sections/FeaturedPosts'
import { useState,useEffect } from 'react'

export default function Home({posts}) { 
  const [width,setWidth] = useState()

  useEffect(()=> {
    window.addEventListener('resize', ()=> {
        console.log(window.innerHeight, window.innerWidth)
        setWidth(window.innerWidth)
    })
 }, [])
  return (
  <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>DemBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {width < 600 ? null: <FeaturedPosts/>}
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-24 lg:mt-8'>
         <div className='lg:col-span-8 col-span-1'> 
         {posts && posts.map((post)=> <PostCard post={post} key={post.title}/>)}
         </div>
         <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget/>
            <Categories/>
          </div>
         </div>
      </div>
    </div>
  )
}

export async function getStaticProps(){
   const posts = (await getPosts()) || [];  
   return {
    props: { posts }
  }
}